import Head from "next/head";

export default function Privacy() {
    return (
        <div>
            <Head>
                <title>Privacy Policy</title>
                <meta
                    name="viewport"
                    content="initial-scale=1.0, width=device-width"
                />
                <meta name="robots" content="index, follow" />
                <meta
                    name="description"
                    content="Privacy Policy Page of Sanjit Sarda's website: This details my privacy policy."
                />
            </Head>
            <h1>Privacy Policy</h1>
            <p>Last updated: January 21st, 2022</p>
            <p>
                This Privacy Policy describes Our policies and procedures on the
                collection, use and disclosure of Your information when You use
                the Service and tells You about Your privacy rights and how the
                law protects You.
            </p>
            <p>
                We use Your Personal data to provide and improve the Service. By
                using the Service, You agree to the collection and use of
                information in accordance with this Privacy Policy. This Privacy
                Policy has been created with the help of the Privacy Policy
                Template.
            </p>
            <h1>Interpretation and Definitions</h1>
            <h2>Interpretation</h2>
            <p>
                The words of which the initial letter is capitalized have
                meanings defined under the following conditions. The following
                definitions shall have the same meaning regardless of whether
                they appear in singular or in plural.
            </p>
            <h2>Definitions</h2>
            <p>For the purposes of this Privacy Policy:</p>
            <p>
                <ul>
                    <li>
                        <b>Account</b> means a unique account created for You to
                        access our Service or parts of our Service.
                    </li>
                    <li>
                        <b>Company</b> (referred to as either "the Company",
                        "We", "Us" or "Our" in this Agreement) refers to Sanjit
                        Sarda :tm: or something. This is not an actual
                        registered trademark for obvious reasons, but if you try
                        to trademark my name, I swear I will{" "}
                        <em>
                            for legal reasons I will not complete this sentence.
                        </em>
                    </li>
                    <li>
                        <b>Cookies</b> are small files that are placed on Your
                        computer, mobile device or any other device by a
                        website, containing the details of Your browsing history
                        on that website among its many uses.
                    </li>
                    <li>
                        <b>Country</b> refers to: California, United States
                    </li>
                    <li>
                        <b>Device</b> means any device that can access the
                        Service such as a computer, a cellphone or a digital
                        tablet.
                    </li>
                    <li>
                        <b>Personal Data</b> is any information that relates to
                        an identified or identifiable individual.
                    </li>
                    <li>
                        <b>Service</b> refers to the Website.
                    </li>
                    <li>
                        <b>Service Provider</b> means any natural or legal
                        person who processes the data on behalf of the Company.
                        It refers to third-party companies or individuals
                        employed by the Company to facilitate the Service, to
                        provide the Service on behalf of the Company, to perform
                        services related to the Service or to assist the Company
                        in analyzing how the Service is used.
                    </li>
                    <li>
                        <b>Usage Data</b> refers to data collected
                        automatically, either generated by the use of the
                        Service or from the Service infrastructure itself (for
                        example, the duration of a page visit).
                    </li>
                    <li>
                        <b>Website</b> refers to Sanjit Sarda, accessible from
                        sanjitsarda.com
                    </li>
                    <li>
                        <b>You</b> means the individual accessing or using the
                        Service, or the company, or other legal entity on behalf
                        of which such individual is accessing or using the
                        Service, as applicable.
                    </li>
                </ul>
            </p>
            <h1>Types of Data Collected</h1>
            <h2>Personal Data</h2>
            <p>
                While using Our Service, We may ask You to provide Us with
                certain personally identifiable information that can be used to
                contact or identify You. Personally identifiable information may
                include, but is not limited to: Usage Data
            </p>
            <h2>Usage Data</h2>
            <p>
                Usage Data is collected automatically when using the Service.
                <br />
                Usage Data may include information such as Your Device's
                Internet Protocol address (e.g. IP address), browser type,
                browser version, the pages of our Service that You visit, the
                time and date of Your visit, the time spent on those pages,
                unique device identifiers and other diagnostic data.
                <br />
                When You access the Service by or through a mobile device, We
                may collect certain information automatically, including, but
                not limited to, the type of mobile device You use, Your mobile
                device unique ID, the IP address of Your mobile device, Your
                mobile operating system, the type of mobile Internet browser You
                use, unique device identifiers and other diagnostic data.
                <br />
                We may also collect information that Your browser sends whenever
                You visit our Service or when You access the Service by or
                through a mobile device.
            </p>
            <p></p>
            <p></p>
        </div>
    );
}
